<template>
  <el-table :data="tableData"
            :span-method="objectSpanMethod"
            border
            style="width: 100%; margin-top: 20px">
    <el-table-column prop="id"
                     label="ID"
                     width="180" />
    <el-table-column prop="name"
                     label="Name" />
    <el-table-column prop="amount1"
                     label="Amount 1" />
    <el-table-column prop="amount2"
                     label="Amount 2" />
    <el-table-column prop="amount3"
                     label="Amount 3" />
  </el-table>
</template>
<script lang="ts" setup>
import type { TableColumnCtx } from 'element-plus/es/components/table/src/table-column/defaults'

interface User {
  id: string
  name: string
  amount1: string
  amount2: string
  amount3: number
}

interface SpanMethodProps {
  row: User
  column: TableColumnCtx<User>
  rowIndex: number
  columnIndex: number
}

const objectSpanMethod = ({ row, column, rowIndex, columnIndex }: SpanMethodProps) => {
  if (columnIndex === 0) {
    if (rowIndex % 2 === 0) {
      return {
        rowspan: 2,
        colspan: 1,
      }
    } else {
      return {
        rowspan: 0,
        colspan: 0,
      }
    }
  }
}
const tableList: User[] = [
  {
    customerList: [
      {
        customerId: '17180',
        customerName: 'am4002',
        expenseAgeList: [
          {
            expenseAmount1: 0,
            expenseAmount10: 0,
            expenseAmount2: 4075.84,
            expenseAmount3: 2037.92,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 1,
            expenseName: '固定租金',
            expenseType: 'R',
            totalAmount: 6113.76,
          },
        ],
        projectId: '964',
        projectName: '联调项目001',
      },
      {
        customerId: '17181',
        customerName: 'am4002-1',
        expenseAgeList: [
          {
            expenseAmount1: 0,
            expenseAmount10: 0,
            expenseAmount2: 4075.84,
            expenseAmount3: 2037.92,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 1,
            expenseName: '固定租金',
            expenseType: 'R',
            totalAmount: 6113.76,
          },
        ],
        projectId: '964',
        projectName: '联调项目001',
      },
      {
        customerId: '17173',
        customerName: 'CD0000001',
        expenseAgeList: [
          {
            expenseAmount1: 13717.9,
            expenseAmount10: 0,
            expenseAmount2: 22386.64,
            expenseAmount3: 28683.41,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 1,
            expenseName: '固定租金',
            expenseType: 'R',
            totalAmount: 64787.95,
          },
          {
            expenseAmount1: 0,
            expenseAmount10: 0,
            expenseAmount2: 1000,
            expenseAmount3: 0,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 4,
            expenseName: '阶梯押金',
            expenseType: 'RD',
            totalAmount: 1000,
          },
          {
            expenseAmount1: 2524.58,
            expenseAmount10: 0,
            expenseAmount2: 5049.16,
            expenseAmount3: 0,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 5,
            expenseName: '保洁费',
            expenseType: 'P',
            totalAmount: 7573.74,
          },
          {
            expenseAmount1: 0,
            expenseAmount10: 0,
            expenseAmount2: 10,
            expenseAmount3: 0,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 6,
            expenseName: '垃圾清运费',
            expenseType: 'O',
            totalAmount: 10,
          },
        ],
        projectId: '964',
        projectName: '联调项目001',
      },
      {
        customerId: '17212',
        customerName: 'easyadd',
        expenseAgeList: [
          {
            expenseAmount1: 2524.58,
            expenseAmount10: 0,
            expenseAmount2: 5049.16,
            expenseAmount3: 0,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 1,
            expenseName: '固定租金',
            expenseType: 'R',
            totalAmount: 7573.74,
          },
        ],
        projectId: '964',
        projectName: '联调项目001',
      },
      {
        customerId: '17214',
        customerName: 'easyadd电子账单',
        expenseAgeList: [
          {
            expenseAmount1: 72006.07,
            expenseAmount10: 0,
            expenseAmount2: 105043.45,
            expenseAmount3: 0,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 1,
            expenseName: '固定租金',
            expenseType: 'R',
            totalAmount: 177049.52,
          },
          {
            expenseAmount1: 0,
            expenseAmount10: 0,
            expenseAmount2: 56081.17,
            expenseAmount3: 0,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 2,
            expenseName: '租金押金',
            expenseType: 'D',
            totalAmount: 56081.17,
          },
          {
            expenseAmount1: 0,
            expenseAmount10: 0,
            expenseAmount2: 21585.68,
            expenseAmount3: 0,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 3,
            expenseName: '固定押金',
            expenseType: 'GD',
            totalAmount: 21585.68,
          },
          {
            expenseAmount1: 60.84,
            expenseAmount10: 0,
            expenseAmount2: 59355.29,
            expenseAmount3: 0,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 4,
            expenseName: '阶梯押金',
            expenseType: 'RD',
            totalAmount: 59416.13,
          },
          {
            expenseAmount1: 18280.42,
            expenseAmount10: 0,
            expenseAmount2: 19831.68,
            expenseAmount3: 0,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 5,
            expenseName: '保洁费',
            expenseType: 'P',
            totalAmount: 38112.1,
          },
          {
            expenseAmount1: 0,
            expenseAmount10: 0,
            expenseAmount2: 3,
            expenseAmount3: 0,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 6,
            expenseName: '垃圾清运费',
            expenseType: 'O',
            totalAmount: 3,
          },
          {
            expenseAmount1: 0,
            expenseAmount10: 0,
            expenseAmount2: 5,
            expenseAmount3: 0,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 7,
            expenseName: '2',
            expenseType: 'T',
            totalAmount: 5,
          },
          {
            expenseAmount1: 0,
            expenseAmount10: 0,
            expenseAmount2: 18,
            expenseAmount3: 0,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 7,
            expenseName: '18',
            expenseType: 'T',
            totalAmount: 18,
          },
        ],
        projectId: '964',
        projectName: '联调项目001',
      },
      {
        customerId: '17213',
        customerName: 'easyadd邮件',
        expenseAgeList: [
          {
            expenseAmount1: 2037.92,
            expenseAmount10: 0,
            expenseAmount2: 4075.84,
            expenseAmount3: 0,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 1,
            expenseName: '固定租金',
            expenseType: 'R',
            totalAmount: 6113.76,
          },
        ],
        projectId: '964',
        projectName: '联调项目001',
      },
      {
        customerId: '17182',
        customerName: 'easydev测试',
        expenseAgeList: [
          {
            expenseAmount1: 1211.8,
            expenseAmount10: 0,
            expenseAmount2: 6398.46,
            expenseAmount3: 2037.92,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 1,
            expenseName: '固定租金',
            expenseType: 'R',
            totalAmount: 9648.18,
          },
          {
            expenseAmount1: 0,
            expenseAmount10: 0,
            expenseAmount2: 2000,
            expenseAmount3: 2037.92,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 2,
            expenseName: '租金押金',
            expenseType: 'D',
            totalAmount: 4037.92,
          },
          {
            expenseAmount1: 0,
            expenseAmount10: 0,
            expenseAmount2: 1211.8,
            expenseAmount3: 0,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 4,
            expenseName: '阶梯押金',
            expenseType: 'RD',
            totalAmount: 1211.8,
          },
        ],
        projectId: '964',
        projectName: '联调项目001',
      },
      {
        customerId: '17211',
        customerName: 'easydev测试税率',
        expenseAgeList: [
          {
            expenseAmount1: 2037.92,
            expenseAmount10: 0,
            expenseAmount2: 4075.84,
            expenseAmount3: 0,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 1,
            expenseName: '固定租金',
            expenseType: 'R',
            totalAmount: 6113.76,
          },
        ],
        projectId: '964',
        projectName: '联调项目001',
      },
      {
        customerId: '17183',
        customerName: 'easyphone测试',
        expenseAgeList: [
          {
            expenseAmount1: 0,
            expenseAmount10: 0,
            expenseAmount2: 4075.84,
            expenseAmount3: 2037.92,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 1,
            expenseName: '固定租金',
            expenseType: 'R',
            totalAmount: 6113.76,
          },
        ],
        projectId: '964',
        projectName: '联调项目001',
      },
      {
        customerId: '17169',
        customerName: 'easy合同签订人',
        expenseAgeList: [
          {
            expenseAmount1: 0,
            expenseAmount10: 0,
            expenseAmount2: 40758.34,
            expenseAmount3: 20379.17,
            expenseAmount4: 0,
            expenseAmount5: 0,
            expenseAmount6: 0,
            expenseAmount7: 0,
            expenseAmount8: 0,
            expenseAmount9: 0,
            expenseIndex: 1,
            expenseName: '固定租金',
            expenseType: 'R',
            totalAmount: 61137.51,
          },
        ],
        projectId: '964',
        projectName: '联调项目001',
      },
    ],
    projectId: '964',
    projectName: '联调项目001',
  },
]
const tableData: User[] = [
  {
    id: '12987122',
    name: 'Tom',
    amount1: '234',
    amount2: '3.2',
    amount3: 10,
  },
  {
    id: '12987123',
    name: 'Tom',
    amount1: '165',
    amount2: '4.43',
    amount3: 12,
  },
  {
    id: '12987124',
    name: 'Tom',
    amount1: '324',
    amount2: '1.9',
    amount3: 9,
  },
  {
    id: '12987125',
    name: 'Tom',
    amount1: '621',
    amount2: '2.2',
    amount3: 17,
  },
  {
    id: '12987126',
    name: 'Tom',
    amount1: '539',
    amount2: '4.1',
    amount3: 15,
  },
]
</script>